NTBSportsDataInput/NTBSportsDataInput/Controllers/MatchManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NTB.SportsDataInput.Application.Models;

namespace NTB.SportsDataInput.Application.Controllers
{
    [Authorize(Roles = "SuperUser,Vaktsjef")]
    public class MatchManagerController : Controller
    {
        //
        // GET: /MatchManager/

        public ActionResult Index()
        {
            var model = new MatchManagementModels();
            if (model.GetMatchManagementListView() != null)
            {
                return View(model.GetMatchManagementListView());
            }

            return View("NoData");
        }

        //
        // GET: /MatchManager/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /MatchManager/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /MatchManager/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        //
        // GET: /MatchManager/Edit/5
 
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /MatchManager/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /MatchManager/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /MatchManager/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult JobSetup(FormCollection collection)
        {
            var model = new MatchManagementModels();
            model.StoreJobs(collection);

            return RedirectToAction("Index");
        }
    }
}

NTBSportsDataInput/NTBSportsDataInput/Controllers/MatchRegisterController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.Security;
using System.Xml;
using System.Xml.Linq;
using System.Xml.XPath;
using NTB.SportsDataInput.Application.Models;
using NTB.SportsDataInput.Domain.Classes;
using O1881.PartnerApi;

namespace NTB.SportsDataInput.Application.Controllers
{
    [Authorize(Roles = "SuperUser,Vaktsjef,Bruker")]
    public class MatchRegisterController : Controller
    {
        //
        // GET: /MatchRegister/

        public ActionResult Index()
        {
            // todo: Need to get the GUID of the logged in user
            // todo: Get the list of matches for today for the district in question
            MembershipUser user = Membership.GetUser(User.Identity.Name);
            Guid guid = new Guid();
            
            if (user != null && user.ProviderUserKey != null)
            {
                guid = new Guid(user.ProviderUserKey.ToString());
            }

            var model = new MatchRegisterModels();

            return View(model.GetUserMatches(guid));
        }

        //
        // GET: /MatchRegister/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /MatchRegister/Create

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SearchContact(int id, FormCollection collection)
        {
            var listofPersons = new List<Person>();

            var searchString = collection["person"].Replace(' ', '+');
            
            string searchQuery =
                @"https://api.1881bedrift.no/search/search?userName=AndersSivesind&password=nyhe2cop3&msisdn=98843575&query=" +
                searchString + "&level=1&catalogueIds=0|5&pageSize=5";
            var testUri = new Uri(searchQuery);

            HttpWebRequest testrequest = (HttpWebRequest) WebRequest.Create(testUri);
            testrequest.Method = "GET";
            testrequest.ContentLength = 0;

            HttpWebResponse testResponse = (HttpWebResponse) testrequest.GetResponse();
            
            XmlNamespaceManager namespaceManager = new XmlNamespaceManager(new NameTable());
            namespaceManager.AddNamespace("empty", "http://1881.no/api/PartnerSearch");
            XDocument doc;
            using (Stream responseStream = testResponse.GetResponseStream())
            {
                
                doc = XDocument.Load(responseStream);
                XNamespace ns = "http://1881.no/api/PartnerSearch";
                

                var resultItems = doc.XPathSelectElements("//empty:ResultItem[empty:ResultType='Person']", namespaceManager);
                foreach (var resultItem in resultItems)
                {
                    var firstname = resultItem.XPathSelectElement("./empty:FirstName", namespaceManager).Value;
                    var lastname = resultItem.XPathSelectElement("./empty:LastName", namespaceManager).Value;
                    var streetAddress = resultItem.XPathSelectElement("./empty:Addresses/empty:Address_Search[empty:AddressType='Visiting']/empty:Street", namespaceManager).Value 
                        + @" "
                        + resultItem.XPathSelectElement("./empty:Addresses/empty:Address_Search[empty:AddressType='Visiting']/empty:StreetId", namespaceManager).Value;
                    var city =
                        resultItem.XPathSelectElement("./empty:Addresses/empty:Address_Search[empty:AddressType='Visiting']/empty:City",
                                                      namespaceManager).Value;
                    var postalCode =
                        resultItem.XPathSelectElement("./empty:Addresses/empty:Address_Search[empty:AddressType='Visiting']/empty:Zip",
                                                      namespaceManager).Value;
                    var mobile =
                        resultItem.XPathSelectElement(
                            "./empty:ContactPoints[empty:ContactPoint_Search/empty:ContactPointType='Mobile']/empty:ContactPoint_Search/empty:Address", namespaceManager)
                                  .Value;

                    var person = new Person
                        {
                            FirstName = firstname,
                            LastName = lastname,
                            PhoneMobile = mobile,
                            City = city,
                            PostalCode = postalCode,
                            StreetAddress = streetAddress
                        };

                    listofPersons.Add(person);
                }

                // /search?userName=<username>&msisdn=<msisdn>&password=<password>&query=<query>&level=0&format=xml
                // https://api.1881bedrift.no/search/search?userName=AndersSivesind&password=nyhe2cop3&msisdn=98843575&query=TEST&level=2&catalogueIds=0|1|5&pageSize=25
            }

            return PartialView(listofPersons);
        }

        //
        // POST: /MatchRegister/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // Post: /MatchRegister/AddComment/MatchId
        [HttpPost]
        public ActionResult AddComment(int id, FormCollection collection)
        {
            // we are to update or insert comment for this match
            string comment = collection["txtBox" + id];
            var model = new MatchRegisterModels();
            var storedComment = model.StoreMatchComment(comment, id);

            return PartialView("AddComment", new MatchComment{
                Comment = storedComment});
        }
        //
        // POST: /MatchRegister/EditContact/5
        [HttpPost]
        public ActionResult EditContact(int id, FormCollection collection)
        {
            var model = new ContactPersonModels();
            var contactPerson = model.UpdateContactPerson(id, collection);

            return Json(contactPerson);
        }

        //
        // Get: /MatchRegister/ChangeStatus/5
        public ActionResult ChangeStatus(int id)
        {
            
            var model = new ContactPersonModels();
            model.ChangeContactPersonStatus(id);

            return RedirectToAction("Index");
        }
        
        //
        // GET: /MatchRegister/Edit/5
 
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /MatchRegister/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /MatchRegister/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /MatchRegister/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

NTBSportsDataInput/NTBSportsDataInput/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@(String.IsNullOrEmpty(ViewBag.Title) ? "Default page title" : ViewBag.Title)</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/ntb_input.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.theme.css")" rel="stylesheet" type="text/css" />
    
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.11.min.js")" type="text/javascript"></script>
    
</head>
    <body>
        <div class="page">
            <div id="header">
                <div id="title">
                    <h1>SportsData Input</h1>
                </div>
                <div id="logindisplay">
                    @Html.Partial("_LogOnPartial")
                </div>
                <div id="menucontainer">
                    <ul id="menu">
                        @{
                            if (Context.User.IsInRole("SuperUser"))
                            {
                                <li>@Html.ActionLink("Brukeradministrasjon", "Index", "UserManager")</li>
                            }

                            if (Context.User.IsInRole("SuperUser") ||
                                Context.User.IsInRole("Vaktsjef"))
                            {
                                <li>@Html.ActionLink("Kampadministrasjon", "Index", "MatchManager", null, new {id="matchreg"})</li>
                            }
                        
                            if (Request.IsAuthenticated)
                            {
                                <li>@Html.ActionLink("Kampregistrering", "Index", "MatchRegister")</li>
                            }
                        }

                        <li>@Html.ActionLink("Hjem", "Index", "Home")</li>
                        <li>@Html.ActionLink("Hjelp", "Help", "Home")</li>
                    </ul>
                </div>
            </div>
            <div id="main">
                @RenderBody()
            </div>
            <div id="footer">
            </div>
        </div>
        
        <div id="loaderspinner" class="loader">
            
        </div>
    
    
    <script type="text/javascript">
        $(document).ready(function () {

            $(".editbox").hide();
            $(".deletebox").hide();
            $(".smsbox").hide();
            $(".searchpersonbox").hide();
            // Find out which page I am actually loading


            $("input[type=submit]").click(function () {
                var formid = this.form.id;
                var matchid = formid.replace('formcomment', '');

                if (formid.substr(0, 11) == "formcomment") {

                    var txtArea = formid.replace('formcomment', 'txtBox');
                    var resultBox = "commentBox" + matchid;

                    $.ajax({
                        type: 'POST',
                        url: '/MatchRegister/AddComment/' + matchid,
                        data: $('#' + formid + ' :input').serialize(),
                        success: function (returndata) {
                            var returnElement = $("#" + resultBox).html($(returndata));
                            var messageIcon = "&nbsp;<img src='Content/images/24x24/comment.png'>";
                            $("#infocol" + matchid).append(messageIcon);
                        },
                        error: function () {
                            alert("error!");
                        }
                    });
                    return false;
                }

                //                if (formid.substr(0, 11) == "editcontact") {

                //                    var personid = formid.replace("editcontact", "");

                //                    // personid = personid.slice(0, personid.lastIndexOf("r"));

                //                    $.ajax({
                //                        type: 'POST',
                //                        url: '/MatchRegister/EditContact/' + personid,
                //                        data: $('#' + formid + ' :input').serialize(),
                //                        success: function (returndata) {
                //                            var returnElement = $("#" + resultBox).html($(returndata));
                //                        },
                //                        error: function () {
                //                            alert("error!");
                //                        }
                //                    });
                //                    return false;
                //                }
            });
            /*
            click
                
            Slow: ajax get data from source = two domains (external sources) - store in database server
                
            Fast: ajax complete -> redirect to new page which gets data to be used from database server

            
            */

            $("#loaderspinner").hide();

            $("a").click(function (ev) {

                var link = $(this).attr('id');
                var href = $(this).attr('href');
                //                alert(location);
                var domain = "http://" + window.location.host;

                var rel = $(this).attr('rel');
                var linkClass = $(this).attr('class');
                var personid = 0;

                var formid = 0;

                // Removed because we are doing this in a separate application
                //                if (link == 'matchreg') {
                //                    ev.preventDefault();
                //                    $("#loaderspinner").show();
                //                    $.get("/MatchManager/MatchManagement", function (data) {
                //                        window.location.href = domain + href;
                //                    });

                //                }

                if (linkClass == "moreinfo") {
                    $("#" + rel).toggle();
                    return false;
                }

                if (linkClass == "searchlink") {

                    var resultBox = rel.replace('search', 'result');
                    personid = rel.replace('search', '');
                    personid = personid.slice(0, personid.lastIndexOf("r"));
                    formid = rel.replace('search', 'findform');

                    $("#" + rel).dialog({

                        resizable: true,
                        height: 400,
                        modal: true,
                        buttons: {
                            'Søk': function () {
                                //                                 Morten Skjeldnes Berre
                                $.ajax({
                                    type: 'POST',
                                    url: '/MatchRegister/SearchContact/' + personid,
                                    data: $('#' + formid + ' :input').serialize(),
                                    success: function (returndata) {
                                        var returnElement = $("#" + resultBox).html($(returndata));

                                    },
                                    error: function () {
                                        alert("error!");
                                    }
                                });
                            },
                            Cancel: function () {
                                $(this).dialog("close");
                            }
                        }
                    });

                    return false;
                }

                if (linkClass == "editlink") {
                    formid = rel.replace('p', 'editcontact');

                    personid = rel.replace('p', '');
                    personid = personid.slice(0, personid.lastIndexOf("r"));


                    $("#" + rel).dialog({
                        resizable: true,
                        height: 450,
                        modal: true,
                        buttons: {
                            'Save': function () {

                                $.ajax({
                                    type: 'POST',
                                    url: '/MatchRegister/EditContact/' + personid,
                                    data: $('#' + formid + ' :input').serialize(),
                                    success: function () {

                                        setTimeout(function () {
                                            location.reload();
                                        }, 0001);

                                        $(this).dialog("close");
                                    },
                                    error: function () {

                                        $(this).dialog("close");
                                    }
                                });
                            },
                            Cancel: function () {
                                $(this).dialog("close");
                            }
                        }
                    });


                    return false;
                }

                if (linkClass == "deletelink") {
                    $("#" + rel).dialog({
                        resizable: false,
                        height: 200,
                        modal: true,
                        buttons: {
                            'Deaktiver': function () {
                                location.href = href;
                                $(this).dialog("close");
                                
                            },
                            Cancel: function () {
                                $(this).dialog("close");
                            }
                        }
                    });

                    return false;
                }

                if (linkClass == "smslink") {
                    $("#" + rel).dialog({
                        resizable: false,
                        height: 250,
                        width: 400,
                        modal: true,
                        buttons: {
                            'Send': function () {
                                $(this).dialog("close");
                            },
                            Cancel: function () {
                                $(this).dialog("close");
                            }
                        }
                    });

                    return false;
                }

                return true;
            });

        });

    </script>
    </body>
</html>

NTBSportsDataInput/NTBSportsDataInput/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Velkommen <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}